# Generated by Django 4.2 on 2026-06-20 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramExcerpt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日期')),
                ('program_name', models.CharField(max_length=200, verbose_name='节目名称')),
                ('time_slot', models.CharField(max_length=100, verbose_name='时段')),
                ('content_summary', models.TextField(verbose_name='内容摘要')),
                ('elderly_notes', models.TextField(blank=True, null=True, verbose_name='老人补充笔记')),
                ('is_duplicate', models.BooleanField(default=False, verbose_name='是否重复')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_excerpts', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='core.programexcerpt', verbose_name='重复主记录')),
            ],
            options={
                'verbose_name': '节目摘录',
                'verbose_name_plural': '节目摘录',
                'db_table': 'program_excerpt',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='专题名称')),
                ('color', models.CharField(max_length=20, verbose_name='颜色')),
                ('icon', models.CharField(max_length=20, verbose_name='图标')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '专题',
                'verbose_name_plural': '专题',
                'db_table': 'topic',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='版本内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('merge_note', models.TextField(blank=True, null=True, verbose_name='合并说明')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_versions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('excerpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.programexcerpt', verbose_name='节目摘录')),
            ],
            options={
                'verbose_name': '版本历史',
                'verbose_name_plural': '版本历史',
                'db_table': 'version',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='programexcerpt',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excerpts', to='core.topic', verbose_name='所属专题'),
        ),
        migrations.CreateModel(
            name='FollowUpItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='事项标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='事项描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=20, verbose_name='优先级')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_follow_ups', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('excerpt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_items', to='core.programexcerpt', verbose_name='关联节目摘录')),
            ],
            options={
                'verbose_name': '待跟进事项',
                'verbose_name_plural': '待跟进事项',
                'db_table': 'follow_up_item',
                'ordering': ['priority', 'due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('excerpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.programexcerpt', verbose_name='节目摘录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comment',
                'ordering': ['-created_at'],
            },
        ),
    ]
