# Generated by Django 4.2 on 2026-06-21 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupitem',
            name='source_type',
            field=models.CharField(choices=[('manual', '手动创建'), ('confirmation', '确认催办')], default='manual', max_length=20, verbose_name='来源类型'),
        ),
        migrations.AddField(
            model_name='programexcerpt',
            name='confirmation_note',
            field=models.TextField(blank=True, null=True, verbose_name='确认备注'),
        ),
        migrations.AddField(
            model_name='programexcerpt',
            name='confirmation_status',
            field=models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('needs_verification', '需核实')], default='pending', max_length=20, verbose_name='确认状态'),
        ),
        migrations.AddField(
            model_name='programexcerpt',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='确认时间'),
        ),
        migrations.AddField(
            model_name='programexcerpt',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_excerpts', to=settings.AUTH_USER_MODEL, verbose_name='确认人'),
        ),
    ]
