# Generated by Django 4.2 on 2026-06-21 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_followupitem_source_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='资料包标题')),
                ('purpose_description', models.TextField(blank=True, null=True, verbose_name='用途说明')),
                ('guide_text', models.TextField(blank=True, null=True, verbose_name='导览语')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_review_packages', to=settings.AUTH_USER_MODEL, verbose_name='创建人（家属）')),
                ('family_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_packages', to='accounts.familygroup', verbose_name='所属家庭组')),
            ],
            options={
                'verbose_name': '回听资料包',
                'verbose_name_plural': '回听资料包',
                'db_table': 'review_package',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='followupitem',
            name='source_type',
            field=models.CharField(choices=[('manual', '手动创建'), ('confirmation', '确认催办'), ('review_package', '资料包讲解需求')], default='manual', max_length=20, verbose_name='来源类型'),
        ),
        migrations.CreateModel(
            name='ReviewPackageItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='阅读顺序')),
                ('is_highlighted', models.BooleanField(default=False, verbose_name='是否重点标记')),
                ('family_reminder', models.TextField(blank=True, null=True, verbose_name='家属提醒')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('excerpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_package_items', to='core.programexcerpt', verbose_name='关联节目摘录')),
                ('review_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.reviewpackage', verbose_name='所属资料包')),
            ],
            options={
                'verbose_name': '资料包条目',
                'verbose_name_plural': '资料包条目',
                'db_table': 'review_package_item',
                'ordering': ['order_index', 'id'],
                'unique_together': {('review_package', 'excerpt')},
            },
        ),
        migrations.CreateModel(
            name='ReviewPackageFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('read', '已读'), ('review_again', '还想再看'), ('needs_explanation', '需要家人讲解')], max_length=30, verbose_name='反馈类型')),
                ('note', models.TextField(blank=True, null=True, verbose_name='补充说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='反馈时间')),
                ('elderly_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='反馈老人')),
                ('package_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.reviewpackageitem', verbose_name='资料包条目')),
            ],
            options={
                'verbose_name': '资料包反馈',
                'verbose_name_plural': '资料包反馈',
                'db_table': 'review_package_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='followupitem',
            name='review_package_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_items', to='core.reviewpackageitem', verbose_name='关联资料包条目'),
        ),
    ]
