# Generated by Django 4.2 on 2026-06-21 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_reviewpackage_alter_followupitem_source_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanionPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='事项标题')),
                ('source_type', models.CharField(choices=[('excerpt', '节目摘录'), ('topic', '专题内容'), ('manual', '手动录入')], default='manual', max_length=20, verbose_name='信息来源')),
                ('source_excerpt_content', models.TextField(blank=True, null=True, verbose_name='来源摘录内容')),
                ('handle_location', models.CharField(max_length=300, verbose_name='办理地点')),
                ('handle_time_start', models.DateField(blank=True, null=True, verbose_name='办理起始日期')),
                ('handle_time_end', models.DateField(blank=True, null=True, verbose_name='办理截止日期')),
                ('handle_time_note', models.CharField(blank=True, max_length=200, null=True, verbose_name='办理时间说明')),
                ('transportation', models.CharField(blank=True, choices=[('walk', '步行'), ('bus', '公交'), ('subway', '地铁'), ('taxi', '打车'), ('private_car', '私家车'), ('community_shuttle', '社区班车'), ('other', '其他')], max_length=30, null=True, verbose_name='出行方式')),
                ('transportation_note', models.CharField(blank=True, max_length=200, null=True, verbose_name='出行方式说明')),
                ('elderly_notes', models.TextField(blank=True, null=True, verbose_name='老人注意事项')),
                ('elderly_concerns', models.TextField(blank=True, null=True, verbose_name='老人担心的问题')),
                ('status', models.CharField(choices=[('pending', '待办理'), ('preparing', '准备中'), ('scheduled', '已预约'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='办理状态')),
                ('materials_confirmed', models.BooleanField(default=False, verbose_name='材料是否已全部确认')),
                ('time_location_known', models.BooleanField(default=False, verbose_name='是否已知晓时间地点')),
                ('needs_companion', models.BooleanField(default=False, verbose_name='是否需要家人陪同')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('companion_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companion_assignments', to=settings.AUTH_USER_MODEL, verbose_name='陪同家属')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_companion_plans', to=settings.AUTH_USER_MODEL, verbose_name='创建人（家属）')),
                ('family_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companion_plans', to='accounts.familygroup', verbose_name='所属家庭组')),
                ('source_excerpt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companion_plans', to='core.programexcerpt', verbose_name='来源节目摘录')),
                ('source_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companion_plans', to='core.topic', verbose_name='来源专题')),
            ],
            options={
                'verbose_name': '陪办计划',
                'verbose_name_plural': '陪办计划',
                'db_table': 'companion_plan',
                'ordering': ['-handle_time_start', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='followupitem',
            name='source_type',
            field=models.CharField(choices=[('manual', '手动创建'), ('confirmation', '确认催办'), ('review_package', '资料包讲解需求'), ('companion_plan', '陪办计划陪同'), ('companion_material', '陪办计划材料确认')], default='manual', max_length=30, verbose_name='来源类型'),
        ),
        migrations.CreateModel(
            name='CompanionPlanMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='材料名称')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='材料说明')),
                ('is_prepared', models.BooleanField(default=False, verbose_name='是否已准备')),
                ('prepared_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('companion_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.companionplan', verbose_name='所属陪办计划')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_materials', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
            ],
            options={
                'verbose_name': '陪办计划材料',
                'verbose_name_plural': '陪办计划材料',
                'db_table': 'companion_plan_material',
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.AddField(
            model_name='followupitem',
            name='companion_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_items', to='core.companionplan', verbose_name='关联陪办计划'),
        ),
    ]
