# Generated by Django 4.2 on 2026-06-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_companionplan_alter_followupitem_source_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companionplan',
            name='handle_time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='办理截止时间'),
        ),
        migrations.AlterField(
            model_name='companionplan',
            name='handle_time_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='办理起始时间'),
        ),
    ]
